NETTOYAGE DE DONNEES COMPLEXES

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("Table_restructure.xlsx")
df.head(12)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,â€¦ and achieving equality for all women and men,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30 Gender inequality in education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MDG,...,MDG,NaN,NaN,NaN,MDG,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,Adult literacya ...,NaN,NaN,NaN,Youth literacya,NaN,NaN,...,NaN,NaN,"Gross tertiary enrolmentb,d",NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,Female rate\n(% aged 15 and older)\n1995-2005,NaN,Ratio of female rate to male rate\n1995-2005,NaN,Female rate\n(% aged 15-24)\n1995-2005,NaN,Ratio of female rate to male rate\n1995-2005,...,Ratio of female rate to male rate\n2005,NaN,Female ratio\n(%)\n2005,NaN,Ratio of female rate to male rate\n2005,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,HDI rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Repositionner la ligne d'en-tÃªte
df = pd.read_excel("Table_restructure.xlsx", header=6)
# https://stackoverflow.com/a/51794989
# Supprimez d'abord toutes les colonnes (axe=1) sans valeurs
df = df.dropna(how="all", axis=1)
# Supprimer toutes les lignes (axe=0) sans valeurs
df = df.dropna(how="all", axis=0).reset_index(drop=True)
df.head(6)

,Unnamed: 0,Unnamed: 1,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MDG,NaN,...,MDG,NaN,NaN,NaN,MDG,NaN,NaN,NaN,MDG,NaN
1,NaN,NaN,Adult literacya ...,NaN,NaN,NaN,Youth literacya,NaN,NaN,NaN,...,NaN,NaN,"Gross secondary enrolmentb,d",NaN,NaN,NaN,"Gross tertiary enrolmentb,d",NaN,NaN,NaN
2,NaN,NaN,Female rate\n(% aged 15 and older)\n1995-2005,NaN,Ratio of female rate to male rate\n1995-2005,NaN,Female rate\n(% aged 15-24)\n1995-2005,NaN,Ratio of female rate to male rate\n1995-2005,NaN,...,Ratio of female rate to male rate\n2005,NaN,Female ratio\n(%)\n2005,NaN,Ratio of female rate to male rate\n2005,NaN,Female ratio\n(%)\n2005,NaN,Ratio of female rate to male rate\n2005,NaN
3,HDI rank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,Iceland,..,NaN,..,NaN,..,NaN,..,NaN,...,0.97,e,109,e,1.03,e,93,e,1.85,e

In [4]:
columns = []
for c in df.columns:
    # Pour chaque colonne, obtenir les valeurs des 5 premiÃ¨res lignes
    # puis conservez toutes les chaÃ®nes (c'est-Ã -dire excluez-les si elles sont nulles) et ajoutez-les en colonne
    columns.append([str(v) for v in df[c][:5] if pd.notnull(v)])
columns

[['HDI rank', 'HIGH HUMAN DEVELOPMENT'],
 [],
 ['Adult literacya                                             ',
  'Female rate\n(% aged 15 and older)\n1995-2005'],
 [],
 ['Ratio of female rate to male rate\n1995-2005'],
 [],
 ['Youth literacya                                  ',
  'Female rate\n(% aged      15-24)\n1995-2005'],
 [],
 ['MDG', 'Ratio of female rate to male rate\n1995-2005'],
 [],
 ['Net primary enrolmentb,c ', 'Female rate\n(%)\n2005'],
 [],
 ['Ratio of female rate to male rate\n2005'],
 [],
 ['Gross primary enrolmentb,d', 'Female ratio\n(%)\n2005'],
 [],
 ['MDG', 'Ratio of female rate to male rate\n2005'],
 [],
 ['Gross secondary enrolmentb,d', 'Female ratio\n(%)\n2005'],
 [],
 ['MDG', 'Ratio of female rate to male rate\n2005'],
 [],
 ['Gross tertiary enrolmentb,d', 'Female ratio\n(%)\n2005'],
 [],
 ['MDG', 'Ratio of female rate to male rate\n2005'],
 []]

In [5]:
columns = [
    "rank",
    "Country",
    "Ad_lit_Fem_rate",
    "Reference 1",
    "Ad_lit_rat_femrate_malrate",
    "Reference 2",
    "Yout_lit_Fem_rate",  
    "Reference 3",
    "Yout_lit_rat_femrate_malrate",
    "Reference 4",
     "Net_prim_enr_fem_rate",
    "Reference 5",
    "Net_prim_enr_rat_femrate_malrate",
    "Reference 6",
    "Gross_prim_enr_fem_rat",   
    "Reference 7",
    "Gross_prim_enr_rat_femrate_malrate",   
    "Reference 8",
    "Gross_sec_enr_femrat",
    "Reference 9",
    "Gross_sec_enr_rat_femrate_malrate",
    "Reference 10",
    "Gross_ tert_enr_female_rat",
    "Reference 11",
    "Gross_tert_enr_rat _femrate_malrate",
    "Reference 12"
]

# RÃ©initialiser les colonnes des cadres de donnÃ©es
df.columns = columns
# Supprimer les lignes qui contenaient les informations dont nous n'avons plus besoin
# et rÃ©initialiser l'index
# np.arange(5) crÃ©e un tableau = [0, 1, 2, 3, 4, 5]
df = df.drop(np.arange(5), axis=0).reset_index(drop=True)
df.head()

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Gross_prim_enr_rat_femrate_malrate,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12
0,1,Iceland,..,NaN,..,NaN,..,NaN,..,NaN,...,0.97,e,109,e,1.03,e,93,e,1.85,e
1,2,Norway,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,NaN,114,NaN,1.01,NaN,97,NaN,1.54,NaN
2,3,Australia,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,144,NaN,0.95,NaN,80,NaN,1.25,NaN
3,4,Canada,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,"e,f",116,"e,f",0.98,"e,f",72,"e,f",1.36,"e,f"
4,5,Ireland,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,118,NaN,1.09,NaN,67,NaN,1.27,NaN

In [6]:
df.head(20)

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Gross_prim_enr_rat_femrate_malrate,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12
0,1,Iceland,..,NaN,..,NaN,..,NaN,..,NaN,...,0.97,e,109,e,1.03,e,93,e,1.85,e
1,2,Norway,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,NaN,114,NaN,1.01,NaN,97,NaN,1.54,NaN
2,3,Australia,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,144,NaN,0.95,NaN,80,NaN,1.25,NaN
3,4,Canada,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,"e,f",116,"e,f",0.98,"e,f",72,"e,f",1.36,"e,f"
4,5,Ireland,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,118,NaN,1.09,NaN,67,NaN,1.27,NaN
5,6,Sweden,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,NaN,103,NaN,1.00,NaN,100,NaN,1.55,NaN
6,7,Switzerland,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,91,NaN,0.93,NaN,43,NaN,0.84,NaN
7,8,Japan,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,NaN,102,NaN,1.00,NaN,52,NaN,0.89,NaN
8,9,Netherlands,..,NaN,..,NaN,..,NaN,..,NaN,...,0.98,NaN,117,NaN,0.98,NaN,63,NaN,1.08,NaN
9,10,France,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,116,NaN,1.00,NaN,64,NaN,1.29,NaN
10,11,Finland,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,113,NaN,1.05,NaN,101,NaN,1.21,NaN
11,12,United States,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,95,NaN,1.02,NaN,97,NaN,1.40,NaN
12,13,Spain,..,NaN,..,NaN,..,NaN,..,NaN,...,0.98,NaN,127,NaN,1.05,NaN,74,NaN,1.22,NaN
13,14,Denmark,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,NaN,126,NaN,1.03,NaN,94,NaN,1.39,NaN
14,15,Austria,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,NaN,100,NaN,0.95,NaN,55,NaN,1.20,NaN
15,16,United Kingdom,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,NaN,107,NaN,1.03,NaN,70,NaN,1.39,NaN
16,17,Belgium,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,108,NaN,0.97,NaN,70,NaN,1.24,NaN
17,18,Luxembourg,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,NaN,97,NaN,1.06,NaN,13,"e,f",1.18,"e,f"
18,19,New Zealand,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,NaN,127,NaN,1.07,NaN,99,NaN,1.50,NaN
19,20,Italy,98.0,NaN,0.99,NaN,99.8,NaN,1.00,NaN,...,0.99,NaN,99,NaN,0.99,NaN,76,NaN,1.36,NaN

In [7]:
df.tail(30)

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Gross_prim_enr_rat_femrate_malrate,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12
169,168,Congo (Democratic Republic of the),54.1,NaN,0.67,NaN,63.1,NaN,0.81,NaN,...,0.78,"e,f",16,"e,f",0.58,"e,f",..,NaN,..,NaN
170,169,Ethiopia,22.8,NaN,0.46,NaN,38.5,NaN,0.62,NaN,...,0.86,NaN,24,NaN,0.65,NaN,1,NaN,0.32,NaN
171,170,Chad,12.8,NaN,0.31,NaN,23.2,NaN,0.42,NaN,...,0.67,NaN,8,e,0.33,e,(.),e,0.14,e
172,171,Central African Republic,33.5,NaN,0.52,NaN,46.9,NaN,0.67,NaN,...,0.66,e,..,NaN,..,NaN,..,NaN,..,NaN
173,172,Mozambique,25.0,NaN,0.46,NaN,36.6,NaN,0.61,NaN,...,0.85,NaN,11,NaN,0.69,NaN,1,NaN,0.49,NaN
174,173,Mali,15.9,NaN,0.49,NaN,16.9,NaN,0.52,NaN,...,0.80,NaN,18,e,0.62,e,2,e,0.47,e
175,174,Niger,15.1,NaN,0.35,NaN,23.2,NaN,0.44,NaN,...,0.73,NaN,7,NaN,0.68,NaN,1,NaN,0.45,NaN
176,175,Guinea-Bissau,..,NaN,..,NaN,..,NaN,..,NaN,...,0.67,"e,f",13,"e,f",0.54,"e,f",(.),"e,f",0.18,"e,f"
177,176,Burkina Faso,16.6,NaN,0.53,NaN,26.5,NaN,0.66,NaN,...,0.80,NaN,12,NaN,0.70,NaN,1,NaN,0.45,NaN
178,177,Sierra Leone,24.2,NaN,0.52,NaN,37.4,NaN,0.63,NaN,...,0.71,f,22,"e,f",0.71,"e,f",1,"e,f",0.40,"e,f"
179,Developing countries,NaN,69.9,NaN,0.91,NaN,81.4,NaN,0.91,NaN,...,0.94,i,58,i,0.93,i,16,i,0.91,i
180,Least developed countries,NaN,44.3,NaN,0.80,NaN,58.0,NaN,0.80,NaN,...,0.89,i,28,i,0.81,i,3,i,0.63,i
181,Arab States,NaN,59.4,NaN,0.88,NaN,79.5,NaN,0.88,NaN,...,0.90,i,65,i,0.92,i,21,i,1.01,i
182,East Asia and the Pacific,NaN,86.7,NaN,0.99,NaN,97.5,NaN,0.99,NaN,...,0.98,i,72,i,1.00,i,21,i,0.93,i
183,Latin America and the Caribbean,NaN,89.7,NaN,1.01,NaN,97.0,NaN,1.01,NaN,...,0.96,i,91,i,1.08,i,32,i,1.17,i
184,South Asia,NaN,47.4,NaN,0.81,NaN,66.6,NaN,0.81,NaN,...,0.93,i,48,i,0.83,i,9,i,0.74,i
185,Sub-Saharan Africa,NaN,51.2,NaN,0.84,NaN,65.1,NaN,0.84,NaN,...,0.89,i,28,i,0.79,i,4,i,0.62,i
186,Central and Eastern Europe and the CIS,NaN,98.7,NaN,1.00,NaN,99.6,NaN,1.00,NaN,...,0.99,i,90,i,0.98,i,63,i,1.30,i
187,OECD,NaN,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,i,98,i,1.00,i,65,i,1.17,i
188,High-income OECD,NaN,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,i,103,i,1.00,i,76,i,1.20,i
189,High human development,NaN,93.6,NaN,1.01,NaN,98.4,NaN,1.01,NaN,...,..,NaN,..,NaN,..,NaN,..,NaN,..,NaN
190,Medium human development,NaN,71.2,NaN,0.92,NaN,83.2,NaN,0.92,NaN,...,..,NaN,..,NaN,..,NaN,..,NaN,..,NaN
191,Low human development,NaN,43.8,NaN,0.80,NaN,58.9,NaN,0.80,NaN,...,..,NaN,..,NaN,..,NaN,..,NaN,..,NaN
192,High income,NaN,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,i,102,i,1.00,i,73,i,1.21,i
193,Middle income,NaN,86.5,NaN,0.99,NaN,96.2,NaN,0.99,NaN,...,0.97,i,78,i,1.01,i,28,i,1.09,i
194,Low income,NaN,48.8,NaN,0.82,NaN,65.8,NaN,0.82,NaN,...,0.91,i,41,i,0.82,i,7,i,0.68,i
195,World,NaN,72.7,NaN,0.92,NaN,82.5,NaN,0.92,NaN,...,0.95,i,64,i,0.94,i,25,i,1.05,i
196,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,a. Data refer to national literacy estimates f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,SOURCES\nColumns 1â€“4: UNESCO Institute for Sta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# DÃ©poser les lignes du bas des donnÃ©es que nous voulons conserver, jusqu'Ã  la fin (dÃ©fini comme len(df))
df = df.drop(np.arange(179,len(df)), axis=0).reset_index(drop=True)

In [9]:
df.tail(50)

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Gross_prim_enr_rat_femrate_malrate,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12
129,129,Solomon Islands,..,NaN,..,NaN,..,NaN,..,NaN,...,0.95,NaN,27,NaN,0.83,NaN,..,NaN,..,NaN
130,130,Lao People's Democratic Republic,60.9,NaN,0.79,NaN,74.7,NaN,0.90,NaN,...,0.88,NaN,40,NaN,0.76,NaN,7,NaN,0.72,NaN
131,131,Cambodia,64.1,NaN,0.76,NaN,78.9,NaN,0.90,NaN,...,0.92,NaN,24,"e,f",0.69,"e,f",2,NaN,0.46,NaN
132,132,Myanmar,86.4,NaN,0.92,NaN,93.4,NaN,0.98,NaN,...,1.02,NaN,40,NaN,0.99,NaN,..,NaN,..,NaN
133,133,Bhutan,..,NaN,..,NaN,..,NaN,..,NaN,...,..,NaN,..,NaN,..,NaN,..,NaN,..,NaN
134,134,Comoros,..,NaN,..,NaN,..,NaN,..,NaN,...,0.88,e,30,e,0.76,e,2,"e,f",0.77,"e,f"
135,135,Ghana,49.8,NaN,0.75,NaN,65.5,NaN,0.86,NaN,...,0.96,NaN,40,e,0.85,e,4,NaN,0.56,NaN
136,136,Pakistan,35.4,NaN,0.55,NaN,53.1,NaN,0.69,NaN,...,0.76,NaN,23,NaN,0.74,NaN,4,NaN,0.88,NaN
137,137,Mauritania,43.4,NaN,0.73,NaN,55.5,NaN,0.82,NaN,...,1.01,NaN,19,NaN,0.85,NaN,2,NaN,0.33,NaN
138,138,Lesotho,90.3,NaN,1.23,NaN,..,NaN,..,NaN,...,1.00,NaN,43,NaN,1.26,NaN,4,NaN,1.27,NaN
139,139,Congo,79.0,g,0.87,g,96.5,g,0.98,g,...,0.92,NaN,35,"e,f",0.84,"e,f",1,"e,f",0.19,"e,f"
140,140,Bangladesh,40.8,NaN,0.76,NaN,60.3,NaN,0.90,NaN,...,1.03,f,48,f,1.03,f,4,NaN,0.53,NaN
141,141,Swaziland,78.3,NaN,0.97,NaN,89.8,NaN,1.03,NaN,...,0.93,e,44,e,0.96,e,5,NaN,1.06,NaN
142,142,Nepal,34.9,NaN,0.56,NaN,60.1,NaN,0.75,NaN,...,0.91,NaN,42,e,0.86,e,3,f,0.40,f
143,143,Madagascar,65.3,NaN,0.85,NaN,68.2,NaN,0.94,NaN,...,0.96,NaN,..,NaN,..,NaN,2,NaN,0.89,NaN
144,144,Cameroon,59.8,NaN,0.78,NaN,..,NaN,..,NaN,...,0.85,e,39,e,0.80,e,5,e,0.66,e
145,145,Papua New Guinea,50.9,NaN,0.80,NaN,64.1,NaN,0.93,NaN,...,0.88,"e,f",23,"e,f",0.79,"e,f",..,NaN,..,NaN
146,146,Haiti,..,NaN,..,NaN,..,NaN,..,NaN,...,..,NaN,..,NaN,..,NaN,..,NaN,..,NaN
147,147,Sudan,51.8,NaN,0.73,NaN,71.4,NaN,0.84,NaN,...,0.87,NaN,33,NaN,0.94,NaN,..,NaN,..,NaN
148,148,Kenya,70.2,NaN,0.90,NaN,80.7,NaN,1.01,NaN,...,0.96,NaN,48,e,0.95,e,2,f,0.60,f
149,149,Djibouti,..,NaN,..,NaN,..,NaN,..,NaN,...,0.82,NaN,19,NaN,0.66,NaN,2,NaN,0.73,NaN
150,150,Timor-Leste,..,NaN,..,NaN,..,NaN,..,NaN,...,0.92,NaN,52,NaN,1.00,NaN,12,"e,f",1.48,"e,f"
151,151,Zimbabwe,86.2,g,0.93,g,97.9,g,1.00,g,...,0.98,f,35,f,0.91,f,3,"e,f",0.63,"e,f"
152,152,Togo,38.5,NaN,0.56,NaN,63.6,NaN,0.76,NaN,...,0.85,NaN,27,e,0.51,e,1,"e,f",0.20,"e,f"
153,153,Yemen,34.7,g,0.47,g,58.9,g,0.65,g,...,0.74,NaN,31,NaN,0.49,NaN,5,NaN,0.37,NaN
154,154,Uganda,57.7,NaN,0.75,NaN,71.2,NaN,0.86,NaN,...,1.00,NaN,17,e,0.81,e,3,f,0.62,f
155,155,Gambia,..,NaN,..,NaN,..,NaN,..,NaN,...,1.06,f,42,f,0.82,f,(.),f,0.23,f
156,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,156,Senegal,29.2,NaN,0.57,NaN,41.0,NaN,0.70,NaN,...,0.97,NaN,18,NaN,0.75,NaN,..,NaN,..,NaN
158,157,Eritrea,..,NaN,..,NaN,..,NaN,..,NaN,...,0.81,NaN,23,NaN,0.59,NaN,(.),f,0.15,f
159,158,Nigeria,60.1,g,0.77,g,81.3,g,0.94,g,...,0.86,NaN,31,NaN,0.84,NaN,7,f,0.55,f
160,159,Tanzania (United Republic of),62.2,NaN,0.80,NaN,76.2,NaN,0.94,NaN,...,0.96,NaN,..,NaN,..,NaN,1,e,0.48,e
161,160,Guinea,18.1,NaN,0.43,NaN,33.7,NaN,0.57,NaN,...,0.84,NaN,21,e,0.53,e,1,NaN,0.24,NaN
162,161,Rwanda,59.8,NaN,0.84,NaN,76.9,NaN,0.98,NaN,...,1.02,e,13,e,0.89,e,2,e,0.62,e
163,162,Angola,54.2,NaN,0.65,NaN,63.2,NaN,0.75,NaN,...,..,NaN,15,f,0.78,f,1,"e,f",0.66,"e,f"
164,163,Benin,23.3,NaN,0.49,NaN,33.2,NaN,0.56,NaN,...,0.80,NaN,23,e,0.57,e,1,"e,f",0.25,"e,f"
165,164,Malawi,54.0,NaN,0.72,NaN,70.7,NaN,0.86,NaN,...,1.02,NaN,25,NaN,0.81,NaN,(.),f,0.54,f
166,165,Zambia,59.8,NaN,0.78,NaN,66.2,NaN,0.91,NaN,...,0.95,NaN,25,e,0.82,e,..,NaN,..,NaN
167,166,CÃ´te d'Ivoire,38.6,NaN,0.63,NaN,52.1,NaN,0.74,NaN,...,0.79,"e,f",18,"e,f",0.55,"e,f",..,NaN,..,NaN
168,167,Burundi,52.2,NaN,0.78,NaN,70.4,NaN,0.92,NaN,...,0.86,NaN,11,e,0.74,e,1,e,0.38,e
169,168,Congo (Democratic Republic of the),54.1,NaN,0.67,NaN,63.1,NaN,0.81,NaN,...,0.78,"e,f",16,"e,f",0.58,"e,f",..,NaN,..,NaN
170,169,Ethiopia,22.8,NaN,0.46,NaN,38.5,NaN,0.62,NaN,...,0.86,NaN,24,NaN,0.65,NaN,1,NaN,0.32,NaN
171,170,Chad,12.8,NaN,0.31,NaN,23.2,NaN,0.42,NaN,...,0.67,NaN,8,e,0.33,e,(.),e,0.14,e
172,171,Central African Republic,33.5,NaN,0.52,NaN,46.9,NaN,0.67,NaN,...,0.66,e,..,NaN,..,NaN,..,NaN,..,NaN
173,172,Mozambique,25.0,NaN,0.46,NaN,36.6,NaN,0.61,NaN,...,0.85,NaN,11,NaN,0.69,NaN,1,NaN,0.49,NaN
174,173,Mali,15.9,NaN,0.49,NaN,16.9,NaN,0.52,NaN,...,0.80,NaN,18,e,0.62,e,2,e,0.47,e
175,174,Niger,15.1,NaN,0.35,NaN,23.2,NaN,0.44,NaN,...,0.73,NaN,7,NaN,0.68,NaN,1,NaN,0.45,NaN
176,175,Guinea-Bissau,..,NaN,..,NaN,..,NaN,..,NaN,...,0.67,"e,f",13,"e,f",0.54,"e,f",(.),"e,f",0.18,"e,f"
177,176,Burkina Faso,16.6,NaN,0.53,NaN,26.5,NaN,0.66,NaN,...,0.80,NaN,12,NaN,0.70,NaN,1,NaN,0.45,NaN
178,177,Sierra Leone,24.2,NaN,0.52,NaN,37.4,NaN,0.63,NaN,...,0.71,f,22,"e,f",0.71,"e,f",1,"e,f",0.40,"e,f"

In [10]:
df.head(90)

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Gross_prim_enr_rat_femrate_malrate,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12
0,1,Iceland,..,NaN,..,NaN,..,NaN,..,NaN,...,0.97,e,109,e,1.03,e,93,e,1.85,e
1,2,Norway,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,NaN,114,NaN,1.01,NaN,97,NaN,1.54,NaN
2,3,Australia,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,144,NaN,0.95,NaN,80,NaN,1.25,NaN
3,4,Canada,..,NaN,..,NaN,..,NaN,..,NaN,...,1.00,"e,f",116,"e,f",0.98,"e,f",72,"e,f",1.36,"e,f"
4,5,Ireland,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,NaN,118,NaN,1.09,NaN,67,NaN,1.27,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,85,Suriname,87.2,NaN,0.95,NaN,94.1,NaN,0.98,NaN,...,1.00,NaN,100,NaN,1.33,NaN,15,f,1.62,f
86,86,Jordan,87.0,NaN,0.91,NaN,99.0,NaN,1.00,NaN,...,1.01,NaN,88,NaN,1.02,NaN,40,NaN,1.06,NaN
87,87,Peru,82.5,NaN,0.88,NaN,96.3,NaN,0.98,NaN,...,1.00,NaN,92,NaN,1.01,NaN,34,e,1.03,e
88,88,Lebanon,..,NaN,..,NaN,..,NaN,..,NaN,...,0.97,NaN,93,NaN,1.10,NaN,54,NaN,1.15,NaN
89,89,Ecuador,89.7,NaN,0.97,NaN,96.5,NaN,1.00,NaN,...,1.00,e,61,e,1.00,e,..,NaN,..,NaN

In [11]:
df.tail(90)

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Gross_prim_enr_rat_femrate_malrate,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12
89,89,Ecuador,89.7,NaN,0.97,NaN,96.5,NaN,1.00,NaN,...,1.00,e,61,e,1.00,e,..,NaN,..,NaN
90,90,Philippines,93.6,NaN,1.02,NaN,96.6,NaN,1.03,NaN,...,0.99,NaN,90,NaN,1.12,NaN,31,NaN,1.23,NaN
91,91,Tunisia,65.3,NaN,0.78,NaN,92.2,NaN,0.96,NaN,...,0.97,NaN,88,NaN,1.09,NaN,35,NaN,1.40,NaN
92,92,Fiji,..,NaN,..,NaN,..,NaN,..,NaN,...,0.98,e,91,e,1.07,e,17,e,1.20,e
93,93,Saint Vincent and the Grenadines,..,NaN,..,NaN,..,NaN,..,NaN,...,0.90,NaN,83,NaN,1.24,NaN,..,NaN,..,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,173,Mali,15.9,NaN,0.49,NaN,16.9,NaN,0.52,NaN,...,0.80,NaN,18,e,0.62,e,2,e,0.47,e
175,174,Niger,15.1,NaN,0.35,NaN,23.2,NaN,0.44,NaN,...,0.73,NaN,7,NaN,0.68,NaN,1,NaN,0.45,NaN
176,175,Guinea-Bissau,..,NaN,..,NaN,..,NaN,..,NaN,...,0.67,"e,f",13,"e,f",0.54,"e,f",(.),"e,f",0.18,"e,f"
177,176,Burkina Faso,16.6,NaN,0.53,NaN,26.5,NaN,0.66,NaN,...,0.80,NaN,12,NaN,0.70,NaN,1,NaN,0.45,NaN
178,177,Sierra Leone,24.2,NaN,0.52,NaN,37.4,NaN,0.63,NaN,...,0.71,f,22,"e,f",0.71,"e,f",1,"e,f",0.40,"e,f"

In [12]:
df.iloc[50:90,:]

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Gross_prim_enr_rat_femrate_malrate,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12
50,51,Cuba,99.8,NaN,1.00,NaN,100.0,NaN,1.00,NaN,...,0.95,NaN,94,NaN,1.00,NaN,78,e,1.72,e
51,52,Mexico,90.2,NaN,0.97,NaN,97.6,NaN,1.00,NaN,...,0.98,NaN,83,NaN,1.07,NaN,24,NaN,0.99,NaN
52,53,Bulgaria,97.7,NaN,0.99,NaN,98.1,NaN,1.00,NaN,...,0.99,NaN,101,NaN,0.95,NaN,47,NaN,1.14,NaN
53,54,Saint Kitts and Nevis,..,NaN,..,NaN,..,NaN,..,NaN,...,1.06,e,93,e,0.98,e,..,NaN,..,NaN
54,55,Tonga,99.0,NaN,1.00,NaN,99.4,NaN,1.00,NaN,...,0.95,e,102,"e,f",1.08,"e,f",8,"e,f",1.67,"e,f"
55,56,Libyan Arab Jamahiriya,74.8,g,0.81,g,96.5,g,0.97,g,...,0.98,NaN,107,e,1.19,e,59,"e,f",1.09,"e,f"
56,57,Antigua and Barbuda,..,NaN,..,NaN,..,NaN,..,NaN,...,..,NaN,..,NaN,..,NaN,..,NaN,..,NaN
57,58,Oman,73.5,NaN,0.85,NaN,96.7,NaN,0.99,NaN,...,1.00,NaN,85,NaN,0.96,NaN,19,NaN,1.09,NaN
58,59,Trinidad and Tobago,97.8,g,0.99,g,99.5,g,1.00,g,...,0.97,e,82,e,1.04,e,14,e,1.27,e
59,60,Romania,96.3,NaN,0.98,NaN,97.8,NaN,1.00,NaN,...,0.99,NaN,86,NaN,1.01,NaN,50,NaN,1.26,NaN
60,61,Saudi Arabia,76.3,NaN,0.87,NaN,94.7,NaN,0.98,NaN,...,1.00,NaN,86,NaN,0.96,NaN,34,NaN,1.47,NaN
61,62,Panama,91.2,NaN,0.99,NaN,95.6,NaN,0.99,NaN,...,0.97,NaN,73,NaN,1.07,NaN,55,NaN,1.63,NaN
62,63,Malaysia,85.4,NaN,0.93,NaN,97.3,NaN,1.00,NaN,...,1.00,f,81,f,1.14,f,36,f,1.31,f
63,64,Belarus,99.4,NaN,1.00,NaN,99.8,NaN,1.00,NaN,...,0.97,NaN,96,NaN,1.01,NaN,72,NaN,1.37,NaN
64,65,Mauritius,80.5,NaN,0.91,NaN,95.4,NaN,1.02,NaN,...,1.00,NaN,88,e,0.99,e,19,NaN,1.26,NaN
65,66,Bosnia and Herzegovina,94.4,NaN,0.95,NaN,99.8,NaN,1.00,NaN,...,..,NaN,..,NaN,..,NaN,..,NaN,..,NaN
66,67,Russian Federation,99.2,NaN,1.00,NaN,99.8,NaN,1.00,NaN,...,1.00,NaN,91,NaN,0.99,NaN,82,e,1.36,e
67,68,Albania,98.3,NaN,0.99,NaN,99.5,NaN,1.00,NaN,...,0.99,f,77,f,0.96,f,23,f,1.57,f
68,69,Macedonia (TFYR),94.1,NaN,0.96,NaN,98.5,NaN,0.99,NaN,...,1.00,NaN,83,NaN,0.98,NaN,35,NaN,1.38,NaN
69,70,Brazil,88.8,NaN,1.00,NaN,97.9,NaN,1.02,NaN,...,0.93,f,111,f,1.10,f,27,f,1.32,f
70,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,71,Dominica,..,NaN,..,NaN,..,NaN,..,NaN,...,0.99,e,106,e,0.97,e,..,NaN,..,NaN
72,72,Saint Lucia,..,NaN,..,NaN,..,NaN,..,NaN,...,0.97,NaN,85,NaN,1.21,NaN,20,NaN,2.80,NaN
73,73,Kazakhstan,99.3,NaN,1.00,NaN,99.9,NaN,1.00,NaN,...,0.99,NaN,97,NaN,0.97,NaN,62,NaN,1.42,NaN
74,74,Venezuela (Bolivarian Republic of),92.7,NaN,0.99,NaN,98.1,NaN,1.02,NaN,...,0.98,NaN,79,NaN,1.13,NaN,41,"e,f",1.08,"e,f"
75,75,Colombia,92.9,NaN,1.00,NaN,98.4,NaN,1.01,NaN,...,0.98,NaN,82,NaN,1.11,NaN,31,NaN,1.09,NaN
76,76,Ukraine,99.2,NaN,0.99,NaN,99.8,NaN,1.00,NaN,...,1.00,NaN,85,NaN,0.92,NaN,75,NaN,1.20,NaN
77,77,Samoa,98.3,g,0.99,g,99.4,g,1.00,g,...,1.00,e,85,e,1.12,e,7,"e,f",0.93,"e,f"
78,78,Thailand,90.5,NaN,0.95,NaN,97.8,NaN,1.00,NaN,...,0.96,h,72,h,1.05,h,44,h,1.06,h
79,79,Dominican Republic,87.2,NaN,1.00,NaN,95.4,NaN,1.03,NaN,...,0.95,NaN,78,NaN,1.21,NaN,41,"e,f",1.64,"e,f"
80,80,Belize,..,NaN,..,NaN,..,NaN,..,NaN,...,0.96,NaN,85,e,1.02,e,4,f,2.43,f
81,81,China,86.5,NaN,0.91,NaN,98.5,NaN,0.99,NaN,...,0.99,e,74,e,1.00,e,20,NaN,0.95,NaN
82,82,Grenada,..,NaN,..,NaN,..,NaN,..,NaN,...,0.96,e,102,e,1.03,e,..,NaN,..,NaN
83,83,Armenia,99.2,NaN,0.99,NaN,99.9,NaN,1.00,NaN,...,1.04,NaN,89,NaN,1.03,NaN,31,NaN,1.22,NaN
84,84,Turkey,79.6,NaN,0.84,NaN,93.3,NaN,0.95,NaN,...,0.95,e,68,e,0.82,e,26,NaN,0.74,NaN
85,85,Suriname,87.2,NaN,0.95,NaN,94.1,NaN,0.98,NaN,...,1.00,NaN,100,NaN,1.33,NaN,15,f,1.62,f
86,86,Jordan,87.0,NaN,0.91,NaN,99.0,NaN,1.00,NaN,...,1.01,NaN,88,NaN,1.02,NaN,40,NaN,1.06,NaN
87,87,Peru,82.5,NaN,0.88,NaN,96.3,NaN,0.98,NaN,...,1.00,NaN,92,NaN,1.01,NaN,34,e,1.03,e
88,88,Lebanon,..,NaN,..,NaN,..,NaN,..,NaN,...,0.97,NaN,93,NaN,1.10,NaN,54,NaN,1.15,NaN
89,89,Ecuador,89.7,NaN,0.97,NaN,96.5,NaN,1.00,NaN,...,1.00,e,61,e,1.00,e,..,NaN,..,NaN

In [13]:
df.tail(50)

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Gross_prim_enr_rat_femrate_malrate,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12
129,129,Solomon Islands,..,NaN,..,NaN,..,NaN,..,NaN,...,0.95,NaN,27,NaN,0.83,NaN,..,NaN,..,NaN
130,130,Lao People's Democratic Republic,60.9,NaN,0.79,NaN,74.7,NaN,0.90,NaN,...,0.88,NaN,40,NaN,0.76,NaN,7,NaN,0.72,NaN
131,131,Cambodia,64.1,NaN,0.76,NaN,78.9,NaN,0.90,NaN,...,0.92,NaN,24,"e,f",0.69,"e,f",2,NaN,0.46,NaN
132,132,Myanmar,86.4,NaN,0.92,NaN,93.4,NaN,0.98,NaN,...,1.02,NaN,40,NaN,0.99,NaN,..,NaN,..,NaN
133,133,Bhutan,..,NaN,..,NaN,..,NaN,..,NaN,...,..,NaN,..,NaN,..,NaN,..,NaN,..,NaN
134,134,Comoros,..,NaN,..,NaN,..,NaN,..,NaN,...,0.88,e,30,e,0.76,e,2,"e,f",0.77,"e,f"
135,135,Ghana,49.8,NaN,0.75,NaN,65.5,NaN,0.86,NaN,...,0.96,NaN,40,e,0.85,e,4,NaN,0.56,NaN
136,136,Pakistan,35.4,NaN,0.55,NaN,53.1,NaN,0.69,NaN,...,0.76,NaN,23,NaN,0.74,NaN,4,NaN,0.88,NaN
137,137,Mauritania,43.4,NaN,0.73,NaN,55.5,NaN,0.82,NaN,...,1.01,NaN,19,NaN,0.85,NaN,2,NaN,0.33,NaN
138,138,Lesotho,90.3,NaN,1.23,NaN,..,NaN,..,NaN,...,1.00,NaN,43,NaN,1.26,NaN,4,NaN,1.27,NaN
139,139,Congo,79.0,g,0.87,g,96.5,g,0.98,g,...,0.92,NaN,35,"e,f",0.84,"e,f",1,"e,f",0.19,"e,f"
140,140,Bangladesh,40.8,NaN,0.76,NaN,60.3,NaN,0.90,NaN,...,1.03,f,48,f,1.03,f,4,NaN,0.53,NaN
141,141,Swaziland,78.3,NaN,0.97,NaN,89.8,NaN,1.03,NaN,...,0.93,e,44,e,0.96,e,5,NaN,1.06,NaN
142,142,Nepal,34.9,NaN,0.56,NaN,60.1,NaN,0.75,NaN,...,0.91,NaN,42,e,0.86,e,3,f,0.40,f
143,143,Madagascar,65.3,NaN,0.85,NaN,68.2,NaN,0.94,NaN,...,0.96,NaN,..,NaN,..,NaN,2,NaN,0.89,NaN
144,144,Cameroon,59.8,NaN,0.78,NaN,..,NaN,..,NaN,...,0.85,e,39,e,0.80,e,5,e,0.66,e
145,145,Papua New Guinea,50.9,NaN,0.80,NaN,64.1,NaN,0.93,NaN,...,0.88,"e,f",23,"e,f",0.79,"e,f",..,NaN,..,NaN
146,146,Haiti,..,NaN,..,NaN,..,NaN,..,NaN,...,..,NaN,..,NaN,..,NaN,..,NaN,..,NaN
147,147,Sudan,51.8,NaN,0.73,NaN,71.4,NaN,0.84,NaN,...,0.87,NaN,33,NaN,0.94,NaN,..,NaN,..,NaN
148,148,Kenya,70.2,NaN,0.90,NaN,80.7,NaN,1.01,NaN,...,0.96,NaN,48,e,0.95,e,2,f,0.60,f
149,149,Djibouti,..,NaN,..,NaN,..,NaN,..,NaN,...,0.82,NaN,19,NaN,0.66,NaN,2,NaN,0.73,NaN
150,150,Timor-Leste,..,NaN,..,NaN,..,NaN,..,NaN,...,0.92,NaN,52,NaN,1.00,NaN,12,"e,f",1.48,"e,f"
151,151,Zimbabwe,86.2,g,0.93,g,97.9,g,1.00,g,...,0.98,f,35,f,0.91,f,3,"e,f",0.63,"e,f"
152,152,Togo,38.5,NaN,0.56,NaN,63.6,NaN,0.76,NaN,...,0.85,NaN,27,e,0.51,e,1,"e,f",0.20,"e,f"
153,153,Yemen,34.7,g,0.47,g,58.9,g,0.65,g,...,0.74,NaN,31,NaN,0.49,NaN,5,NaN,0.37,NaN
154,154,Uganda,57.7,NaN,0.75,NaN,71.2,NaN,0.86,NaN,...,1.00,NaN,17,e,0.81,e,3,f,0.62,f
155,155,Gambia,..,NaN,..,NaN,..,NaN,..,NaN,...,1.06,f,42,f,0.82,f,(.),f,0.23,f
156,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,156,Senegal,29.2,NaN,0.57,NaN,41.0,NaN,0.70,NaN,...,0.97,NaN,18,NaN,0.75,NaN,..,NaN,..,NaN
158,157,Eritrea,..,NaN,..,NaN,..,NaN,..,NaN,...,0.81,NaN,23,NaN,0.59,NaN,(.),f,0.15,f
159,158,Nigeria,60.1,g,0.77,g,81.3,g,0.94,g,...,0.86,NaN,31,NaN,0.84,NaN,7,f,0.55,f
160,159,Tanzania (United Republic of),62.2,NaN,0.80,NaN,76.2,NaN,0.94,NaN,...,0.96,NaN,..,NaN,..,NaN,1,e,0.48,e
161,160,Guinea,18.1,NaN,0.43,NaN,33.7,NaN,0.57,NaN,...,0.84,NaN,21,e,0.53,e,1,NaN,0.24,NaN
162,161,Rwanda,59.8,NaN,0.84,NaN,76.9,NaN,0.98,NaN,...,1.02,e,13,e,0.89,e,2,e,0.62,e
163,162,Angola,54.2,NaN,0.65,NaN,63.2,NaN,0.75,NaN,...,..,NaN,15,f,0.78,f,1,"e,f",0.66,"e,f"
164,163,Benin,23.3,NaN,0.49,NaN,33.2,NaN,0.56,NaN,...,0.80,NaN,23,e,0.57,e,1,"e,f",0.25,"e,f"
165,164,Malawi,54.0,NaN,0.72,NaN,70.7,NaN,0.86,NaN,...,1.02,NaN,25,NaN,0.81,NaN,(.),f,0.54,f
166,165,Zambia,59.8,NaN,0.78,NaN,66.2,NaN,0.91,NaN,...,0.95,NaN,25,e,0.82,e,..,NaN,..,NaN
167,166,CÃ´te d'Ivoire,38.6,NaN,0.63,NaN,52.1,NaN,0.74,NaN,...,0.79,"e,f",18,"e,f",0.55,"e,f",..,NaN,..,NaN
168,167,Burundi,52.2,NaN,0.78,NaN,70.4,NaN,0.92,NaN,...,0.86,NaN,11,e,0.74,e,1,e,0.38,e
169,168,Congo (Democratic Republic of the),54.1,NaN,0.67,NaN,63.1,NaN,0.81,NaN,...,0.78,"e,f",16,"e,f",0.58,"e,f",..,NaN,..,NaN
170,169,Ethiopia,22.8,NaN,0.46,NaN,38.5,NaN,0.62,NaN,...,0.86,NaN,24,NaN,0.65,NaN,1,NaN,0.32,NaN
171,170,Chad,12.8,NaN,0.31,NaN,23.2,NaN,0.42,NaN,...,0.67,NaN,8,e,0.33,e,(.),e,0.14,e
172,171,Central African Republic,33.5,NaN,0.52,NaN,46.9,NaN,0.67,NaN,...,0.66,e,..,NaN,..,NaN,..,NaN,..,NaN
173,172,Mozambique,25.0,NaN,0.46,NaN,36.6,NaN,0.61,NaN,...,0.85,NaN,11,NaN,0.69,NaN,1,NaN,0.49,NaN
174,173,Mali,15.9,NaN,0.49,NaN,16.9,NaN,0.52,NaN,...,0.80,NaN,18,e,0.62,e,2,e,0.47,e
175,174,Niger,15.1,NaN,0.35,NaN,23.2,NaN,0.44,NaN,...,0.73,NaN,7,NaN,0.68,NaN,1,NaN,0.45,NaN
176,175,Guinea-Bissau,..,NaN,..,NaN,..,NaN,..,NaN,...,0.67,"e,f",13,"e,f",0.54,"e,f",(.),"e,f",0.18,"e,f"
177,176,Burkina Faso,16.6,NaN,0.53,NaN,26.5,NaN,0.66,NaN,...,0.80,NaN,12,NaN,0.70,NaN,1,NaN,0.45,NaN
178,177,Sierra Leone,24.2,NaN,0.52,NaN,37.4,NaN,0.63,NaN,...,0.71,f,22,"e,f",0.71,"e,f",1,"e,f",0.40,"e,f"

In [14]:
hdi_categories = ["HIGH HUMAN DEVELOPMENT", "MEDIUM HUMAN DEVELOPMENT", "LOW HUMAN DEVELOPMENT"]
# Se dÃ©barrasser des rangÃ©es avec les catÃ©gories HDI
# https://stackoverflow.com/a/27360130 & https://stackoverflow.com/a/12098586
df = df.drop(df[df["rank"].isin(hdi_categories)].index, axis=0).reset_index(drop=True)
# RÃ©fÃ©rence pour np.where https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html
# Pensez que cela ressemble Ã  une dÃ©claration du type "if" : where(test est vrai, vrai-quelque chose, faux-quelque chose)
# ceci peut aussi Ãªtre imbriquÃ© : where(test is true, true-thing, where(new-test is true, true-thing, false-thing))
df.loc[:, "HDI category"] = np.where(df["rank"] > 155,
                                     "LOW HUMAN DEVELOPMENT",
                                     np.where(df["rank"] < 71,
                                              "HIGH HUMAN DEVELOPMENT",
                                              "MEDIUM HUMAN DEVELOPMENT"
                                              
                                             )
                                    )
df.sort_values(by="rank", inplace=True)
df.head()

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12,HDI category
0,1,Iceland,..,NaN,..,NaN,..,NaN,..,NaN,...,e,109,e,1.03,e,93,e,1.85,e,HIGH HUMAN DEVELOPMENT
1,2,Norway,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,114,NaN,1.01,NaN,97,NaN,1.54,NaN,HIGH HUMAN DEVELOPMENT
2,3,Australia,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,144,NaN,0.95,NaN,80,NaN,1.25,NaN,HIGH HUMAN DEVELOPMENT
3,4,Canada,..,NaN,..,NaN,..,NaN,..,NaN,...,"e,f",116,"e,f",0.98,"e,f",72,"e,f",1.36,"e,f",HIGH HUMAN DEVELOPMENT
4,5,Ireland,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,118,NaN,1.09,NaN,67,NaN,1.27,NaN,HIGH HUMAN DEVELOPMENT

In [15]:
df.head(70)

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12,HDI category
0,1,Iceland,..,NaN,..,NaN,..,NaN,..,NaN,...,e,109,e,1.03,e,93,e,1.85,e,HIGH HUMAN DEVELOPMENT
1,2,Norway,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,114,NaN,1.01,NaN,97,NaN,1.54,NaN,HIGH HUMAN DEVELOPMENT
2,3,Australia,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,144,NaN,0.95,NaN,80,NaN,1.25,NaN,HIGH HUMAN DEVELOPMENT
3,4,Canada,..,NaN,..,NaN,..,NaN,..,NaN,...,"e,f",116,"e,f",0.98,"e,f",72,"e,f",1.36,"e,f",HIGH HUMAN DEVELOPMENT
4,5,Ireland,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,118,NaN,1.09,NaN,67,NaN,1.27,NaN,HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,66,Bosnia and Herzegovina,94.4,NaN,0.95,NaN,99.8,NaN,1.00,NaN,...,NaN,..,NaN,..,NaN,..,NaN,..,NaN,HIGH HUMAN DEVELOPMENT
66,67,Russian Federation,99.2,NaN,1.00,NaN,99.8,NaN,1.00,NaN,...,NaN,91,NaN,0.99,NaN,82,e,1.36,e,HIGH HUMAN DEVELOPMENT
67,68,Albania,98.3,NaN,0.99,NaN,99.5,NaN,1.00,NaN,...,f,77,f,0.96,f,23,f,1.57,f,HIGH HUMAN DEVELOPMENT
68,69,Macedonia (TFYR),94.1,NaN,0.96,NaN,98.5,NaN,0.99,NaN,...,NaN,83,NaN,0.98,NaN,35,NaN,1.38,NaN,HIGH HUMAN DEVELOPMENT
69,70,Brazil,88.8,NaN,1.00,NaN,97.9,NaN,1.02,NaN,...,f,111,f,1.10,f,27,f,1.32,f,HIGH HUMAN DEVELOPMENT

In [16]:
df.tail(50)

,rank,Country,Ad_lit_Fem_rate,Reference 1,Ad_lit_rat_femrate_malrate,Reference 2,Yout_lit_Fem_rate,Reference 3,Yout_lit_rat_femrate_malrate,Reference 4,...,Reference 8,Gross_sec_enr_femrat,Reference 9,Gross_sec_enr_rat_femrate_malrate,Reference 10,Gross_ tert_enr_female_rat,Reference 11,Gross_tert_enr_rat _femrate_malrate,Reference 12,HDI category
127,128,India,47.8,NaN,0.65,NaN,67.7,NaN,0.80,NaN,...,e,50,NaN,0.80,NaN,9,NaN,0.70,NaN,MEDIUM HUMAN DEVELOPMENT
128,129,Solomon Islands,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,27,NaN,0.83,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT
129,130,Lao People's Democratic Republic,60.9,NaN,0.79,NaN,74.7,NaN,0.90,NaN,...,NaN,40,NaN,0.76,NaN,7,NaN,0.72,NaN,MEDIUM HUMAN DEVELOPMENT
130,131,Cambodia,64.1,NaN,0.76,NaN,78.9,NaN,0.90,NaN,...,NaN,24,"e,f",0.69,"e,f",2,NaN,0.46,NaN,MEDIUM HUMAN DEVELOPMENT
131,132,Myanmar,86.4,NaN,0.92,NaN,93.4,NaN,0.98,NaN,...,NaN,40,NaN,0.99,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT
132,133,Bhutan,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,..,NaN,..,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT
133,134,Comoros,..,NaN,..,NaN,..,NaN,..,NaN,...,e,30,e,0.76,e,2,"e,f",0.77,"e,f",MEDIUM HUMAN DEVELOPMENT
134,135,Ghana,49.8,NaN,0.75,NaN,65.5,NaN,0.86,NaN,...,NaN,40,e,0.85,e,4,NaN,0.56,NaN,MEDIUM HUMAN DEVELOPMENT
135,136,Pakistan,35.4,NaN,0.55,NaN,53.1,NaN,0.69,NaN,...,NaN,23,NaN,0.74,NaN,4,NaN,0.88,NaN,MEDIUM HUMAN DEVELOPMENT
136,137,Mauritania,43.4,NaN,0.73,NaN,55.5,NaN,0.82,NaN,...,NaN,19,NaN,0.85,NaN,2,NaN,0.33,NaN,MEDIUM HUMAN DEVELOPMENT
137,138,Lesotho,90.3,NaN,1.23,NaN,..,NaN,..,NaN,...,NaN,43,NaN,1.26,NaN,4,NaN,1.27,NaN,MEDIUM HUMAN DEVELOPMENT
138,139,Congo,79.0,g,0.87,g,96.5,g,0.98,g,...,NaN,35,"e,f",0.84,"e,f",1,"e,f",0.19,"e,f",MEDIUM HUMAN DEVELOPMENT
139,140,Bangladesh,40.8,NaN,0.76,NaN,60.3,NaN,0.90,NaN,...,f,48,f,1.03,f,4,NaN,0.53,NaN,MEDIUM HUMAN DEVELOPMENT
140,141,Swaziland,78.3,NaN,0.97,NaN,89.8,NaN,1.03,NaN,...,e,44,e,0.96,e,5,NaN,1.06,NaN,MEDIUM HUMAN DEVELOPMENT
141,142,Nepal,34.9,NaN,0.56,NaN,60.1,NaN,0.75,NaN,...,NaN,42,e,0.86,e,3,f,0.40,f,MEDIUM HUMAN DEVELOPMENT
142,143,Madagascar,65.3,NaN,0.85,NaN,68.2,NaN,0.94,NaN,...,NaN,..,NaN,..,NaN,2,NaN,0.89,NaN,MEDIUM HUMAN DEVELOPMENT
143,144,Cameroon,59.8,NaN,0.78,NaN,..,NaN,..,NaN,...,e,39,e,0.80,e,5,e,0.66,e,MEDIUM HUMAN DEVELOPMENT
144,145,Papua New Guinea,50.9,NaN,0.80,NaN,64.1,NaN,0.93,NaN,...,"e,f",23,"e,f",0.79,"e,f",..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT
145,146,Haiti,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,..,NaN,..,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT
146,147,Sudan,51.8,NaN,0.73,NaN,71.4,NaN,0.84,NaN,...,NaN,33,NaN,0.94,NaN,..,NaN,..,NaN,MEDIUM HUMAN DEVELOPMENT
147,148,Kenya,70.2,NaN,0.90,NaN,80.7,NaN,1.01,NaN,...,NaN,48,e,0.95,e,2,f,0.60,f,MEDIUM HUMAN DEVELOPMENT
148,149,Djibouti,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,19,NaN,0.66,NaN,2,NaN,0.73,NaN,MEDIUM HUMAN DEVELOPMENT
149,150,Timor-Leste,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,52,NaN,1.00,NaN,12,"e,f",1.48,"e,f",MEDIUM HUMAN DEVELOPMENT
150,151,Zimbabwe,86.2,g,0.93,g,97.9,g,1.00,g,...,f,35,f,0.91,f,3,"e,f",0.63,"e,f",MEDIUM HUMAN DEVELOPMENT
151,152,Togo,38.5,NaN,0.56,NaN,63.6,NaN,0.76,NaN,...,NaN,27,e,0.51,e,1,"e,f",0.20,"e,f",MEDIUM HUMAN DEVELOPMENT
152,153,Yemen,34.7,g,0.47,g,58.9,g,0.65,g,...,NaN,31,NaN,0.49,NaN,5,NaN,0.37,NaN,MEDIUM HUMAN DEVELOPMENT
153,154,Uganda,57.7,NaN,0.75,NaN,71.2,NaN,0.86,NaN,...,NaN,17,e,0.81,e,3,f,0.62,f,MEDIUM HUMAN DEVELOPMENT
154,155,Gambia,..,NaN,..,NaN,..,NaN,..,NaN,...,f,42,f,0.82,f,(.),f,0.23,f,MEDIUM HUMAN DEVELOPMENT
155,156,Senegal,29.2,NaN,0.57,NaN,41.0,NaN,0.70,NaN,...,NaN,18,NaN,0.75,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT
156,157,Eritrea,..,NaN,..,NaN,..,NaN,..,NaN,...,NaN,23,NaN,0.59,NaN,(.),f,0.15,f,LOW HUMAN DEVELOPMENT
157,158,Nigeria,60.1,g,0.77,g,81.3,g,0.94,g,...,NaN,31,NaN,0.84,NaN,7,f,0.55,f,LOW HUMAN DEVELOPMENT
158,159,Tanzania (United Republic of),62.2,NaN,0.80,NaN,76.2,NaN,0.94,NaN,...,NaN,..,NaN,..,NaN,1,e,0.48,e,LOW HUMAN DEVELOPMENT
159,160,Guinea,18.1,NaN,0.43,NaN,33.7,NaN,0.57,NaN,...,NaN,21,e,0.53,e,1,NaN,0.24,NaN,LOW HUMAN DEVELOPMENT
160,161,Rwanda,59.8,NaN,0.84,NaN,76.9,NaN,0.98,NaN,...,e,13,e,0.89,e,2,e,0.62,e,LOW HUMAN DEVELOPMENT
161,162,Angola,54.2,NaN,0.65,NaN,63.2,NaN,0.75,NaN,...,NaN,15,f,0.78,f,1,"e,f",0.66,"e,f",LOW HUMAN DEVELOPMENT
162,163,Benin,23.3,NaN,0.49,NaN,33.2,NaN,0.56,NaN,...,NaN,23,e,0.57,e,1,"e,f",0.25,"e,f",LOW HUMAN DEVELOPMENT
163,164,Malawi,54.0,NaN,0.72,NaN,70.7,NaN,0.86,NaN,...,NaN,25,NaN,0.81,NaN,(.),f,0.54,f,LOW HUMAN DEVELOPMENT
164,165,Zambia,59.8,NaN,0.78,NaN,66.2,NaN,0.91,NaN,...,NaN,25,e,0.82,e,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT
165,166,CÃ´te d'Ivoire,38.6,NaN,0.63,NaN,52.1,NaN,0.74,NaN,...,"e,f",18,"e,f",0.55,"e,f",..,NaN,..,NaN,LOW HUMAN DEVELOPMENT
166,167,Burundi,52.2,NaN,0.78,NaN,70.4,NaN,0.92,NaN,...,NaN,11,e,0.74,e,1,e,0.38,e,LOW HUMAN DEVELOPMENT
167,168,Congo (Democratic Republic of the),54.1,NaN,0.67,NaN,63.1,NaN,0.81,NaN,...,"e,f",16,"e,f",0.58,"e,f",..,NaN,..,NaN,LOW HUMAN DEVELOPMENT
168,169,Ethiopia,22.8,NaN,0.46,NaN,38.5,NaN,0.62,NaN,...,NaN,24,NaN,0.65,NaN,1,NaN,0.32,NaN,LOW HUMAN DEVELOPMENT
169,170,Chad,12.8,NaN,0.31,NaN,23.2,NaN,0.42,NaN,...,NaN,8,e,0.33,e,(.),e,0.14,e,LOW HUMAN DEVELOPMENT
170,171,Central African Republic,33.5,NaN,0.52,NaN,46.9,NaN,0.67,NaN,...,e,..,NaN,..,NaN,..,NaN,..,NaN,LOW HUMAN DEVELOPMENT
171,172,Mozambique,25.0,NaN,0.46,NaN,36.6,NaN,0.61,NaN,...,NaN,11,NaN,0.69,NaN,1,NaN,0.49,NaN,LOW HUMAN DEVELOPMENT
172,173,Mali,15.9,NaN,0.49,NaN,16.9,NaN,0.52,NaN,...,NaN,18,e,0.62,e,2,e,0.47,e,LOW HUMAN DEVELOPMENT
173,174,Niger,15.1,NaN,0.35,NaN,23.2,NaN,0.44,NaN,...,NaN,7,NaN,0.68,NaN,1,NaN,0.45,NaN,LOW HUMAN DEVELOPMENT
174,175,Guinea-Bissau,..,NaN,..,NaN,..,NaN,..,NaN,...,"e,f",13,"e,f",0.54,"e,f",(.),"e,f",0.18,"e,f",LOW HUMAN DEVELOPMENT
175,176,Burkina Faso,16.6,NaN,0.53,NaN,26.5,NaN,0.66,NaN,...,NaN,12,NaN,0.70,NaN,1,NaN,0.45,NaN,LOW HUMAN DEVELOPMENT
176,177,Sierra Leone,24.2,NaN,0.52,NaN,37.4,NaN,0.63,NaN,...,f,22,"e,f",0.71,"e,f",1,"e,f",0.40,"e,f",LOW HUMAN DEVELOPMENT